import "../styles/globals.css";

import { Metadata } from "next";

import { spaceGrotesk } from "~/styles/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${spaceGrotesk.variable} bg-white text-stone-700 dark:bg-stone-900 dark:text-stone-300 antialiased font-display`}
      >
        {children}
      </body>
    </html>
  );
}
